buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.0'
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'com.lamoushi.ads'
    compileSdk 33

    defaultConfig {
        minSdk 21
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    // --- هذا هو السطر السحري الذي سيحل مشكلة غيت هيب ---
    // يفرض على الملف الناتج أن يكون اسمه LamoushiAds-release.aar
    base {
        archivesName = "LamoushiAds"
    }
    // -----------------------------------------------
}

repositories {
    google()
    mavenCentral()
    maven { url 'https://jitpack.io' } 
    maven { url "https://plugins.gradle.org/m2/" }
}

dependencies {
    compileOnly "org.godotengine:godot:4.2.0.stable"
}
