name: Build Android Plugin
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate Gradle Wrapper
        run: |
          cd android-plugin
          gradle wrapper --gradle-version 8.5

      - name: Build with Gradle
        run: |
          cd android-plugin
          chmod +x gradlew
          ./gradlew assembleRelease

      # نستخدم النجمة هنا لضمان العثور على الملف وتغيير اسمه فوراً
      - name: Rename AAR for Consistency
        run: |
          mv android-plugin/build/outputs/aar/*.aar android-plugin/build/outputs/aar/LamoushiAds-release.aar

      - name: Create GDAP File
        run: |
          cat <<EOF > android-plugin/build/outputs/aar/LamoushiAds.gdap
          [config]
          name="LamoushiAds"
          binary_type="local"
          binary="LamoushiAds-release.aar"

          [dependencies]
          local=[]
          remote=[]
          custom_rules=[]
          EOF

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LamoushiAds_Plugin_Ready
          path: |
            android-plugin/build/outputs/aar/LamoushiAds-release.aar
            android-plugin/build/outputs/aar/LamoushiAds.gdap
