name: Build Android Plugin
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # تحديث لـ v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4 # تحديث لـ v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x android-plugin/gradlew
          cd android-plugin
          ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # هذا هو التغيير الأهم لـ v4
        with:
          name: GodotAndroidPlugin
          path: android-plugin/build/outputs/aar/*.aar
